name: Build

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get -qy install libsqlite3-dev
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Cache shards
        uses: actions/cache@v3
        with:
          path: lib
          key: ${{ runner.os }}-shards-${{ hashFiles('**/shard.lock', '.github/workflows/ci.yml', '.github/workflows/deploy.yml') }}
      - name: Install shards
        run: shards check || shards install
      - name: Check formatting
        run: crystal tool format --check
      - name: Run specs
        run: crystal spec
      - name: Build
        run: shards build --production
